version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci

  build:
    commands:
      - export NODE_TLS_REJECT_UNAUTHORIZED=0
      - npm run build

artifacts:
  files:
    - "**/*"
    - ".platform/**/*"
    - ".ebextensions/**/*"
  exclude-paths:
    - "node_modules/**/*"
    - ".git/**/*"
  discard-paths: no